name: Manual Workflow with Secrets and Variables

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment (staging/production)'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      version:
        description: 'Enter the version number'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: '1.0.0'  # A variable (non-sensitive)
      DEPLOY_ENV: ${{ github.event.inputs.environment }}  # Variable from manual input

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print environment and version
        run: |
          echo "Deploying version ${{ github.event.inputs.version }} to $DEPLOY_ENV environment"
          echo "App Version: $APP_VERSION"

      - name: Use secret in the workflow
        run: |
          echo "Using secret API key: ${{ secrets.MY_SECRET_API_KEY }}"  # Secret from GitHub Secrets
        env:
          API_KEY: ${{ secrets.MY_SECRET_API_KEY }}  # You can pass secrets as environment variables
